apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: fase4automoveis
  name: fase4automoveis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fase4automoveis
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/fase-3-sub-fase4automoveisnetwork: "true"
        io.kompose.service: fase4automoveis
    spec:
      containers:
        - image: wellingt0npires/fase4automoveis:latest
          name: fase4automoveis
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 900m
              memory: 900Mi
      restartPolicy: Always
      