apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  init.sql: |
    ALTER USER postgres PASSWORD '123';
    CREATE TABLE veiculos(marca VARCHAR(50), modelo VARCHAR(50), ano VARCHAR(50), cor VARCHAR(50), preco REAL, flagvendido BOOLEAN, pagamento BOOLEAN, pagamentodesc VARCHAR(100), cpf VARCHAR(12), datavenda DATE, id SERIAL);
    CREATE TABLE usuario(login VARCHAR(50), password VARCHAR(50), email VARCHAR(50), cpf VARCHAR(12), admin BOOLEAN);