apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: vendas-fase5automoveis
  name: vendas-fase5automoveis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vendas-fase5automoveis
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/fase-3-sub-fase5automoveisnetwork: "true"
        io.kompose.service: vendas-fase5automoveis
    spec:
      containers:
        - image: wellingt0npires/vendas-fase5automoveis:latest
          name: vendas-fase5automoveis
          ports:
            - containerPort: 8086
              hostPort: 8086
              protocol: TCP
          resources:
            requests:
              cpu: 900m
              memory: 900Mi
      restartPolicy: Always